name = "cloudflare-docker-proxy"
compatibility_date = "2023-12-01"

[dev]
ip = "0.0.0.0"
port = 8787
local_protocol = "http"

[env.vars]
CUSTOM_DOMAIN = ""

[env.dev.vars]
MODE = "debug"
TARGET_UPSTREAM = "https://registry-1.docker.io"
CUSTOM_DOMAIN = "exmaple.com"

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.

[env.production]
name = "cloudflare-proxy"

[env.production.vars]
MODE = "production"
TARGET_UPSTREAM = ""

